### ISSUE TITLE
Problemas para chamar a biblioteca libsndfile

### ISSUE THREAD

**Issue by LeDSantos** [schramm/compmus_2020_1#1]
Olá, utilizei o code blocks no Windows e configurei da seguinte forma:
em Project - Build options - aba Search directories - adicionar o diretório da biblioteca com  ..\..\..\..\..\Program Files\Mega-Nerd\libsndfile\include
aba Linker settings - adicionar o diretório com a biblioteca ..\..\..\..\..\Program Files\Mega-Nerd\libsndfile\lib\libsndfile-1.lib
Quando vou compilar aparece undefined reference to funções da biblioteca.
Alguém sabe onde pode estar o erro ou outra forma de compilar?

**Comment by schramm** [comment]
Oi Letícia, 

Não tenho MS Windows aqui para testar aqui. Mas, basicamente, tu precisas apontar para os Headers (\Program Files\Mega-Nerd\libsndfile\include) e para os .lib (.\Program Files\Mega-Nerd\libsndfile\lib\libsndfile-1.lib). Por favor, verifica se esses são os nomes corretos dos arquivos.  Alguém mais conseguiu compilar para windows?

PS. Sugiro vocês usarem Linux. A vida de vocês vai ser muito mais divertida.

Best,
Rodrigo

**Comment by LeDSantos** [comment]
Acabei fazendo tudo numa maquina virtual linux, a meus problemas acabaram.
